import { Inter } from 'next/font/google'
import { StyledComponentsRegistry } from '@/lib/registry'
import { LayoutProvider } from './LayoutProvider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <LayoutProvider>{children}</LayoutProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
