import { Inter } from 'next/font/google'
import { StyledComponentsRegistry } from '@/lib/registry'
import { Cookies } from '@/lib/cookies'
import { Navbar, Footer } from '@/components'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Navbar />
          {children}
          <Footer />
        </StyledComponentsRegistry>
        <Cookies />
      </body>
    </html>
  )
}