export async function generateMetadata({ params }: { params: { id: string } }) {
  return {
    title: 'Blog',
    description: 'Generated by create next app | Blog',
  }
}

export default function Page({ params }: { params: { id: string } }) {
  return <h1>Blog ID: {params.id}</h1>
}
